### ISSUE TITLE
 Moduł raportowy

### ISSUE THREAD

**Issue by janek2j** [infoshareacademy/jcszr8-Gity#131]
Jako administrator systemu chciałbym mieć dostęp do raportów o wykorzystywaniu danych, aby wiedzieć co preferują użytkownicy i czy nasz system jest używany i przez jak liczne grono.

Założenia:

moduł ten jest oddzielną aplikacją (jest oddzielnie uruchamiany)
moduł ten udostępnia REST API, z którego powinna korzystać główna aplikacja (wysyłać dane i pobierać je w formie raportu)
generowanie raportu na żądanie z istniejącej aplikacji www
jakie dane będą wysyłane i jaki raport będzie generowany? Decyzja zespołu

- [x] Aplikacja z API
- [x] Generowanie raportu na żądanie i dostarczenie do administratora
- [x] Komunikacja istniejącej aplikacji web z nowym API

https://jira.is-academy.pl/browse/JCSZR8G-35

**Comment by PatrykWiacek** [comment]
sorry ze sie tu wladowalem ale chcialem to dokonczyc bo mam teraz duzo wolnego czasu zeby dopchnac projekt do konca
