### ISSUE TITLE
W jaki sposób przechowywać ustawienia dla projektu/solucji

### ISSUE THREAD

**Issue by janek2j** [infoshareacademy/jcszr8-Gity#18]
W jaki sposób przechowywać ustawienia dla projektu/solucji tak, aby były widoczne wszędzie.

Kwestia jest taka, że na ten moment utworzona została klasa AppConfig w projekcie CarRental.ConsoleUI i pola z tej klasy są widoczne dla tego projektu ale nie dla innych (bez dodawania dependencies).

Więc w jaki "poprawny" sposób należy przechowywać konfigurację dla projektów/solucji w .NET....

**Comment by PatrykSzwer** [comment]
Zazwyczaj do przechowywania tego typu konfiguracji używamy IConfiguration i pliku appsettings.json. Jak będziecie mieli aplikacje webową to utworzy i skonfiguruje wam się to samo, ale w konsolowce trzeba to dodać ręcznie: https://dev.to/iamrule/add-your-appsettingsjson-to-a-c-console-application-5gd6

Takiej konfiguracji współdzielonej na całą solucje raczej się nie robi, ew używa się do tego jakiegoś uwspólnionego projektu, ale raczej nie powinniście mieć takiej potrzeby.

**Comment by janek2j** [comment]
Dzięki. Zamykam issue
